<h3>Movie Prediction App Project</h3>

Creating a flask based application which can recommend movies based on a film the user selects from a dropdown box (limited to the film selection of the dataset).

<h5>Data Exploration + Formatting:

In [2]:
import pandas as pd
import numpy as np

In [7]:
credits = pd.read_csv('data/tmdb_5000_credits.csv')
movies = pd.read_csv('data/tmdb_5000_movies.csv')

/var/folders/bw/y81spjm11x78s7y1l9x977qc0000gn/T/ipykernel_11214/2431300199.py:1: DtypeWarning: Columns (0: movie_id, 1: title, 2: cast, 3: crew, 4: Unnamed: 4, 5: Unnamed: 5, 6: Unnamed: 6, 7: Unnamed: 7, 8: Unnamed: 8, 9: Unnamed: 9, 10: Unnamed: 10, 11: Unnamed: 11, 12: Unnamed: 12, 13: Unnamed: 13, 14: Unnamed: 14, 15: Unnamed: 15, 16: Unnamed: 16, 17: Unnamed: 17, 18: Unnamed: 18, 19: Unnamed: 19, 20: Unnamed: 20, 21: Unnamed: 21, 22: Unnamed: 22, 23: Unnamed: 23, 24: Unnamed: 24, 25: Unnamed: 25, 26: Unnamed: 26, 27: Unnamed: 27, 28: Unnamed: 28, 29: Unnamed: 29, 30: Unnamed: 30, 31: Unnamed: 31, 32: Unnamed: 32, 33: Unnamed: 33, 34: Unnamed: 34, 35: Unnamed: 35, 36: Unnamed: 36, 37: Unnamed: 37, 38: Unnamed: 38, 39: Unnamed: 39, 40: Unnamed: 40, 41: Unnamed: 41, 42: Unnamed: 42, 43: Unnamed: 43, 44: Unnamed: 44, 45: Unnamed: 45, 46: Unnamed: 46, 47: Unnamed: 47, 48: Unnamed: 48, 49: Unnamed: 49, 50: Unnamed: 50, 51: Unnamed: 51, 52: Unnamed: 52, 53: Unnamed: 53, 54: Unnamed: 54, 55: Unnamed: 55, 56: Unnamed: 56, 57: Unnamed: 57, 58: Unnamed: 58, 59: Unnamed: 59, 60: Unnamed: 60, 61: Unnamed: 61, 62: Unnamed: 62, 63: Unnamed: 63, 64: Unnamed: 64, 65: Unnamed: 65, 66: Unnamed: 66, 67: Unnamed: 67, 68: Unnamed: 68, 69: Unnamed: 69, 70: Unnamed: 70, 71: Unnamed: 71, 72: Unnamed: 72, 73: Unnamed: 73, 74: Unnamed: 74, 75: Unnamed: 75, 76: Unnamed: 76, 77: Unnamed: 77, 78: Unnamed: 78, 79: Unnamed: 79, 80: Unnamed: 80, 81: Unnamed: 81, 82: Unnamed: 82, 83: Unnamed: 83, 84: Unnamed: 84, 85: Unnamed: 85, 86: Unnamed: 86, 87: Unnamed: 87, 88: Unnamed: 88, 89: Unnamed: 89, 90: Unnamed: 90, 91: Unnamed: 91, 92: Unnamed: 92, 93: Unnamed: 93, 94: Unnamed: 94, 95: Unnamed: 95, 96: Unnamed: 96, 97: Unnamed: 97, 98: Unnamed: 98, 99: Unnamed: 99, 100: Unnamed: 100, 101: Unnamed: 101, 102: Unnamed: 102, 103: Unnamed: 103, 104: Unnamed: 104, 105: Unnamed: 105, 106: Unnamed: 106, 107: Unnamed: 107, 108: Unnamed: 108, 109: Unnamed: 109, 110: Unnamed: 110, 111: Unnamed: 111, 112: Unnamed: 112, 113: Unnamed: 113, 114: Unnamed: 114, 115: Unnamed: 115, 116: Unnamed: 116, 117: Unnamed: 117, 118: Unnamed: 118, 119: Unnamed: 119, 120: Unnamed: 120, 121: Unnamed: 121, 122: Unnamed: 122, 123: Unnamed: 123, 124: Unnamed: 124, 125: Unnamed: 125, 126: Unnamed: 126, 127: Unnamed: 127, 128: Unnamed: 128, 129: Unnamed: 129, 130: Unnamed: 130, 131: Unnamed: 131, 132: Unnamed: 132, 133: Unnamed: 133, 134: Unnamed: 134, 135: Unnamed: 135, 136: Unnamed: 136, 137: Unnamed: 137, 138: Unnamed: 138, 139: Unnamed: 139, 140: Unnamed: 140, 141: Unnamed: 141, 142: Unnamed: 142, 143: Unnamed: 143, 144: Unnamed: 144, 145: Unnamed: 145, 146: Unnamed: 146, 147: Unnamed: 147, 148: Unnamed: 148, 149: Unnamed: 149, 150: Unnamed: 150, 151: Unnamed: 151, 152: Unnamed: 152, 153: Unnamed: 153, 154: Unnamed: 154, 155: Unnamed: 155, 156: Unnamed: 156, 157: Unnamed: 157, 158: Unnamed: 158, 159: Unnamed: 159, 160: Unnamed: 160, 161: Unnamed: 161, 162: Unnamed: 162, 163: Unnamed: 163, 164: Unnamed: 164, 165: Unnamed: 165, 166: Unnamed: 166, 167: Unnamed: 167, 168: Unnamed: 168, 169: Unnamed: 169, 170: Unnamed: 170, 171: Unnamed: 171, 172: Unnamed: 172, 173: Unnamed: 173, 174: Unnamed: 174, 175: Unnamed: 175, 176: Unnamed: 176, 177: Unnamed: 177, 178: Unnamed: 178, 179: Unnamed: 179, 180: Unnamed: 180, 181: Unnamed: 181, 182: Unnamed: 182, 183: Unnamed: 183, 184: Unnamed: 184, 185: Unnamed: 185, 186: Unnamed: 186, 187: Unnamed: 187, 188: Unnamed: 188, 189: Unnamed: 189, 190: Unnamed: 190, 191: Unnamed: 191, 192: Unnamed: 192, 193: Unnamed: 193, 194: Unnamed: 194, 195: Unnamed: 195, 196: Unnamed: 196, 197: Unnamed: 197, 198: Unnamed: 198, 199: Unnamed: 199, 200: Unnamed: 200, 201: Unnamed: 201, 202: Unnamed: 202, 203: Unnamed: 203, 204: Unnamed: 204, 205: Unnamed: 205, 206: Unnamed: 206, 207: Unnamed: 207, 208: Unnamed: 208, 209: Unnamed: 209, 210: Unnamed: 210, 211: Unnamed: 211, 212: Unnamed: 212, 213: Unnamed: 213, 214: Unnamed: 214, 215: Unnamed: 215, 216: Unnamed: 216, 217: Unnamed: 217, 218: Unnamed: 218, 219: Unnamed: 219, 220: Unnamed: 220, 221: Unnamed: 221, 222: Unnamed: 222, 223: Unnamed: 223, 224: Unnamed: 224, 225: Unnamed: 225, 226: Unnamed: 226, 227: Unnamed: 227, 228: Unnamed: 228, 229: Unnamed: 229, 230: Unnamed: 230, 231: Unnamed: 231, 232: Unnamed: 232, 233: Unnamed: 233, 234: Unnamed: 234, 235: Unnamed: 235, 236: Unnamed: 236, 237: Unnamed: 237, 238: Unnamed: 238, 239: Unnamed: 239, 240: Unnamed: 240, 241: Unnamed: 241, 242: Unnamed: 242, 243: Unnamed: 243, 244: Unnamed: 244, 245: Unnamed: 245, 246: Unnamed: 246, 247: Unnamed: 247, 248: Unnamed: 248, 249: Unnamed: 249, 250: Unnamed: 250, 251: Unnamed: 251, 252: Unnamed: 252, 253: Unnamed: 253, 254: Unnamed: 254, 255: Unnamed: 255, 256: Unnamed: 256, 257: Unnamed: 257, 258: Unnamed: 258, 259: Unnamed: 259, 260: Unnamed: 260, 261: Unnamed: 261, 262: Unnamed: 262, 263: Unnamed: 263, 264: Unnamed: 264, 265: Unnamed: 265, 266: Unnamed: 266, 267: Unnamed: 267, 268: Unnamed: 268, 269: Unnamed: 269, 270: Unnamed: 270, 271: Unnamed: 271, 272: Unnamed: 272, 273: Unnamed: 273, 274: Unnamed: 274, 275: Unnamed: 275, 276: Unnamed: 276, 277: Unnamed: 277, 278: Unnamed: 278, 279: Unnamed: 279, 280: Unnamed: 280, 281: Unnamed: 281, 282: Unnamed: 282, 283: Unnamed: 283, 284: Unnamed: 284, 285: Unnamed: 285, 286: Unnamed: 286, 287: Unnamed: 287, 288: Unnamed: 288, 289: Unnamed: 289, 290: Unnamed: 290, 291: Unnamed: 291, 292: Unnamed: 292, 293: Unnamed: 293, 294: Unnamed: 294, 295: Unnamed: 295, 296: Unnamed: 296, 297: Unnamed: 297, 298: Unnamed: 298, 299: Unnamed: 299, 300: Unnamed: 300, 301: Unnamed: 301, 302: Unnamed: 302, 303: Unnamed: 303, 304: Unnamed: 304, 305: Unnamed: 305, 306: Unnamed: 306, 307: Unnamed: 307, 308: Unnamed: 308, 309: Unnamed: 309, 310: Unnamed: 310, 311: Unnamed: 311, 312: Unnamed: 312, 313: Unnamed: 313, 314: Unnamed: 314, 315: Unnamed: 315, 316: Unnamed: 316, 317: Unnamed: 317, 318: Unnamed: 318, 319: Unnamed: 319, 320: Unnamed: 320, 321: Unnamed: 321, 322: Unnamed: 322, 323: Unnamed: 323, 324: Unnamed: 324, 325: Unnamed: 325, 326: Unnamed: 326, 327: Unnamed: 327, 328: Unnamed: 328, 329: Unnamed: 329, 330: Unnamed: 330, 331: Unnamed: 331, 332: Unnamed: 332, 333: Unnamed: 333, 334: Unnamed: 334, 335: Unnamed: 335, 336: Unnamed: 336, 337: Unnamed: 337, 338: Unnamed: 338, 339: Unnamed: 339, 340: Unnamed: 340, 341: Unnamed: 341, 342: Unnamed: 342, 343: Unnamed: 343, 344: Unnamed: 344, 345: Unnamed: 345, 346: Unnamed: 346, 347: Unnamed: 347, 348: Unnamed: 348, 349: Unnamed: 349, 350: Unnamed: 350, 351: Unnamed: 351, 352: Unnamed: 352, 353: Unnamed: 353, 354: Unnamed: 354, 355: Unnamed: 355, 356: Unnamed: 356, 357: Unnamed: 357, 358: Unnamed: 358, 359: Unnamed: 359, 360: Unnamed: 360, 361: Unnamed: 361, 362: Unnamed: 362, 363: Unnamed: 363, 364: Unnamed: 364, 365: Unnamed: 365, 366: Unnamed: 366, 367: Unnamed: 367, 368: Unnamed: 368, 369: Unnamed: 369, 370: Unnamed: 370, 371: Unnamed: 371, 372: Unnamed: 372, 373: Unnamed: 373, 374: Unnamed: 374, 375: Unnamed: 375, 376: Unnamed: 376, 377: Unnamed: 377, 378: Unnamed: 378, 379: Unnamed: 379, 380: Unnamed: 380, 381: Unnamed: 381, 382: Unnamed: 382, 383: Unnamed: 383, 384: Unnamed: 384, 385: Unnamed: 385, 386: Unnamed: 386, 387: Unnamed: 387, 388: Unnamed: 388, 389: Unnamed: 389, 390: Unnamed: 390, 391: Unnamed: 391, 392: Unnamed: 392, 393: Unnamed: 393, 394: Unnamed: 394, 395: Unnamed: 395, 396: Unnamed: 396, 397: Unnamed: 397, 398: Unnamed: 398, 399: Unnamed: 399, 400: Unnamed: 400, 401: Unnamed: 401, 402: Unnamed: 402, 403: Unnamed: 403, 404: Unnamed: 404, 405: Unnamed: 405, 406: Unnamed: 406, 407: Unnamed: 407, 408: Unnamed: 408, 409: Unnamed: 409, 410: Unnamed: 410, 411: Unnamed: 411, 412: Unnamed: 412, 413: Unnamed: 413, 414: Unnamed: 414, 415: Unnamed: 415, 416: Unnamed: 416, 417: Unnamed: 417, 418: Unnamed: 418, 419: Unnamed: 419, 420: Unnamed: 420, 421: Unnamed: 421, 422: Unnamed: 422, 423: Unnamed: 423, 424: Unnamed: 424, 425: Unnamed: 425, 426: Unnamed: 426, 427: Unnamed: 427, 428: Unnamed: 428, 429: Unnamed: 429, 430: Unnamed: 430, 431: Unnamed: 431, 432: Unnamed: 432, 433: Unnamed: 433, 434: Unnamed: 434, 435: Unnamed: 435, 436: Unnamed: 436, 437: Unnamed: 437, 438: Unnamed: 438, 439: Unnamed: 439, 440: Unnamed: 440, 441: Unnamed: 441, 442: Unnamed: 442, 443: Unnamed: 443, 444: Unnamed: 444, 445: Unnamed: 445, 446: Unnamed: 446, 447: Unnamed: 447, 448: Unnamed: 448, 449: Unnamed: 449, 450: Unnamed: 450, 451: Unnamed: 451, 452: Unnamed: 452, 453: Unnamed: 453, 454: Unnamed: 454, 455: Unnamed: 455, 456: Unnamed: 456, 457: Unnamed: 457, 458: Unnamed: 458, 459: Unnamed: 459, 460: Unnamed: 460, 461: Unnamed: 461, 462: Unnamed: 462, 463: Unnamed: 463, 464: Unnamed: 464, 465: Unnamed: 465, 466: Unnamed: 466, 467: Unnamed: 467, 468: Unnamed: 468, 469: Unnamed: 469, 470: Unnamed: 470, 471: Unnamed: 471, 472: Unnamed: 472, 473: Unnamed: 473, 474: Unnamed: 474, 475: Unnamed: 475, 476: Unnamed: 476, 477: Unnamed: 477, 478: Unnamed: 478, 479: Unnamed: 479, 480: Unnamed: 480, 481: Unnamed: 481, 482: Unnamed: 482, 483: Unnamed: 483, 484: Unnamed: 484, 485: Unnamed: 485, 486: Unnamed: 486, 487: Unnamed: 487, 488: Unnamed: 488, 489: Unnamed: 489, 490: Unnamed: 490, 491: Unnamed: 491, 492: Unnamed: 492, 493: Unnamed: 493, 494: Unnamed: 494, 495: Unnamed: 495, 496: Unnamed: 496, 497: Unnamed: 497, 498: Unnamed: 498, 499: Unnamed: 499, 500: Unnamed: 500, 501: Unnamed: 501, 502: Unnamed: 502, 503: Unnamed: 503, 504: Unnamed: 504, 505: Unnamed: 505, 506: Unnamed: 506, 507: Unnamed: 507, 508: Unnamed: 508, 509: Unnamed: 509, 510: Unnamed: 510, 511: Unnamed: 511, 512: Unnamed: 512, 513: Unnamed: 513, 514: Unnamed: 514, 515: Unnamed: 515, 516: Unnamed: 516, 517: Unnamed: 517, 518: Unnamed: 518, 519: Unnamed: 519, 520: Unnamed: 520, 521: Unnamed: 521, 522: Unnamed: 522, 523: Unnamed: 523, 524: Unnamed: 524, 525: Unnamed: 525, 526: Unnamed: 526, 527: Unnamed: 527, 528: Unnamed: 528, 529: Unnamed: 529, 530: Unnamed: 530, 531: Unnamed: 531, 532: Unnamed: 532, 533: Unnamed: 533, 534: Unnamed: 534, 535: Unnamed: 535, 536: Unnamed: 536, 537: Unnamed: 537, 538: Unnamed: 538, 539: Unnamed: 539, 540: Unnamed: 540, 541: Unnamed: 541, 542: Unnamed: 542, 543: Unnamed: 543, 544: Unnamed: 544, 545: Unnamed: 545, 546: Unnamed: 546, 547: Unnamed: 547, 548: Unnamed: 548, 549: Unnamed: 549, 550: Unnamed: 550, 551: Unnamed: 551, 552: Unnamed: 552, 553: Unnamed: 553, 554: Unnamed: 554, 555: Unnamed: 555, 556: Unnamed: 556, 557: Unnamed: 557, 558: Unnamed: 558, 559: Unnamed: 559, 560: Unnamed: 560, 561: Unnamed: 561, 562: Unnamed: 562, 563: Unnamed: 563, 564: Unnamed: 564, 565: Unnamed: 565, 566: Unnamed: 566, 567: Unnamed: 567, 568: Unnamed: 568, 569: Unnamed: 569, 570: Unnamed: 570, 571: Unnamed: 571, 572: Unnamed: 572, 573: Unnamed: 573, 574: Unnamed: 574, 575: Unnamed: 575, 576: Unnamed: 576, 577: Unnamed: 577, 578: Unnamed: 578, 579: Unnamed: 579, 580: Unnamed: 580, 581: Unnamed: 581, 582: Unnamed: 582, 583: Unnamed: 583, 584: Unnamed: 584, 585: Unnamed: 585, 586: Unnamed: 586, 587: Unnamed: 587, 588: Unnamed: 588, 589: Unnamed: 589, 590: Unnamed: 590, 591: Unnamed: 591, 592: Unnamed: 592, 593: Unnamed: 593, 594: Unnamed: 594, 595: Unnamed: 595, 596: Unnamed: 596, 597: Unnamed: 597, 598: Unnamed: 598, 599: Unnamed: 599, 600: Unnamed: 600, 601: Unnamed: 601, 602: Unnamed: 602, 603: Unnamed: 603, 604: Unnamed: 604, 605: Unnamed: 605, 606: Unnamed: 606, 607: Unnamed: 607, 608: Unnamed: 608, 609: Unnamed: 609, 610: Unnamed: 610, 611: Unnamed: 611, 612: Unnamed: 612, 613: Unnamed: 613, 614: Unnamed: 614, 615: Unnamed: 615, 616: Unnamed: 616, 617: Unnamed: 617, 618: Unnamed: 618, 619: Unnamed: 619, 620: Unnamed: 620, 621: Unnamed: 621, 622: Unnamed: 622, 623: Unnamed: 623, 624: Unnamed: 624, 625: Unnamed: 625, 626: Unnamed: 626, 627: Unnamed: 627, 628: Unnamed: 628, 629: Unnamed: 629, 630: Unnamed: 630, 631: Unnamed: 631, 632: Unnamed: 632, 633: Unnamed: 633, 634: Unnamed: 634, 635: Unnamed: 635, 636: Unnamed: 636, 637: Unnamed: 637, 638: Unnamed: 638, 639: Unnamed: 639, 640: Unnamed: 640, 641: Unnamed: 641, 642: Unnamed: 642, 643: Unnamed: 643, 644: Unnamed: 644, 645: Unnamed: 645, 646: Unnamed: 646, 647: Unnamed: 647, 648: Unnamed: 648, 649: Unnamed: 649, 650: Unnamed: 650, 651: Unnamed: 651, 652: Unnamed: 652, 653: Unnamed: 653, 654: Unnamed: 654, 655: Unnamed: 655, 656: Unnamed: 656, 657: Unnamed: 657, 658: Unnamed: 658, 659: Unnamed: 659, 660: Unnamed: 660, 661: Unnamed: 661, 662: Unnamed: 662, 663: Unnamed: 663, 664: Unnamed: 664, 665: Unnamed: 665, 666: Unnamed: 666, 667: Unnamed: 667, 668: Unnamed: 668, 669: Unnamed: 669, 670: Unnamed: 670, 671: Unnamed: 671, 672: Unnamed: 672, 673: Unnamed: 673, 674: Unnamed: 674, 675: Unnamed: 675, 676: Unnamed: 676, 677: Unnamed: 677, 678: Unnamed: 678, 679: Unnamed: 679, 680: Unnamed: 680, 681: Unnamed: 681, 682: Unnamed: 682, 683: Unnamed: 683, 684: Unnamed: 684, 685: Unnamed: 685, 686: Unnamed: 686, 687: Unnamed: 687, 688: Unnamed: 688, 689: Unnamed: 689, 690: Unnamed: 690, 691: Unnamed: 691, 692: Unnamed: 692, 693: Unnamed: 693, 694: Unnamed: 694, 695: Unnamed: 695, 696: Unnamed: 696, 697: Unnamed: 697, 698: Unnamed: 698, 699: Unnamed: 699, 700: Unnamed: 700, 701: Unnamed: 701, 702: Unnamed: 702, 703: Unnamed: 703, 704: Unnamed: 704, 705: Unnamed: 705, 706: Unnamed: 706, 707: Unnamed: 707, 708: Unnamed: 708, 709: Unnamed: 709, 710: Unnamed: 710, 711: Unnamed: 711, 712: Unnamed: 712, 713: Unnamed: 713, 714: Unnamed: 714, 715: Unnamed: 715, 716: Unnamed: 716, 717: Unnamed: 717, 718: Unnamed: 718, 719: Unnamed: 719, 720: Unnamed: 720, 721: Unnamed: 721, 722: Unnamed: 722, 723: Unnamed: 723, 724: Unnamed: 724, 725: Unnamed: 725, 726: Unnamed: 726, 727: Unnamed: 727, 728: Unnamed: 728, 729: Unnamed: 729, 730: Unnamed: 730, 731: Unnamed: 731, 732: Unnamed: 732, 733: Unnamed: 733, 734: Unnamed: 734, 735: Unnamed: 735, 736: Unnamed: 736, 737: Unnamed: 737, 738: Unnamed: 738, 739: Unnamed: 739, 740: Unnamed: 740, 741: Unnamed: 741, 742: Unnamed: 742, 743: Unnamed: 743, 744: Unnamed: 744, 745: Unnamed: 745, 746: Unnamed: 746, 747: Unnamed: 747, 748: Unnamed: 748, 749: Unnamed: 749, 750: Unnamed: 750, 751: Unnamed: 751, 752: Unnamed: 752, 753: Unnamed: 753, 754: Unnamed: 754, 755: Unnamed: 755, 756: Unnamed: 756, 757: Unnamed: 757, 758: Unnamed: 758, 759: Unnamed: 759, 760: Unnamed: 760, 761: Unnamed: 761, 762: Unnamed: 762, 763: Unnamed: 763, 764: Unnamed: 764, 765: Unnamed: 765, 766: Unnamed: 766, 767: Unnamed: 767, 768: Unnamed: 768, 769: Unnamed: 769, 770: Unnamed: 770, 771: Unnamed: 771, 772: Unnamed: 772, 773: Unnamed: 773, 774: Unnamed: 774, 775: Unnamed: 775, 776: Unnamed: 776, 777: Unnamed: 777, 778: Unnamed: 778, 779: Unnamed: 779, 780: Unnamed: 780, 781: Unnamed: 781, 782: Unnamed: 782, 783: Unnamed: 783, 784: Unnamed: 784, 785: Unnamed: 785, 786: Unnamed: 786, 787: Unnamed: 787, 788: Unnamed: 788, 789: Unnamed: 789, 790: Unnamed: 790, 791: Unnamed: 791, 792: Unnamed: 792, 793: Unnamed: 793, 794: Unnamed: 794, 795: Unnamed: 795, 796: Unnamed: 796, 797: Unnamed: 797, 798: Unnamed: 798, 799: Unnamed: 799, 800: Unnamed: 800, 801: Unnamed: 801, 802: Unnamed: 802, 803: Unnamed: 803, 804: Unnamed: 804, 805: Unnamed: 805, 806: Unnamed: 806, 807: Unnamed: 807, 808: Unnamed: 808, 809: Unnamed: 809, 810: Unnamed: 810, 811: Unnamed: 811, 812: Unnamed: 812, 813: Unnamed: 813, 814: Unnamed: 814, 815: Unnamed: 815, 816: Unnamed: 816, 817: Unnamed: 817, 818: Unnamed: 818, 819: Unnamed: 819, 820: Unnamed: 820, 821: Unnamed: 821, 822: Unnamed: 822, 823: Unnamed: 823, 824: Unnamed: 824, 825: Unnamed: 825, 826: Unnamed: 826, 827: Unnamed: 827, 828: Unnamed: 828, 829: Unnamed: 829, 830: Unnamed: 830, 831: Unnamed: 831, 832: Unnamed: 832, 833: Unnamed: 833, 834: Unnamed: 834, 835: Unnamed: 835, 836: Unnamed: 836, 837: Unnamed: 837, 838: Unnamed: 838, 839: Unnamed: 839, 840: Unnamed: 840, 841: Unnamed: 841, 842: Unnamed: 842, 843: Unnamed: 843, 844: Unnamed: 844, 845: Unnamed: 845, 846: Unnamed: 846, 847: Unnamed: 847, 848: Unnamed: 848, 849: Unnamed: 849, 850: Unnamed: 850, 851: Unnamed: 851, 852: Unnamed: 852, 853: Unnamed: 853, 854: Unnamed: 854, 855: Unnamed: 855, 856: Unnamed: 856, 857: Unnamed: 857, 858: Unnamed: 858, 859: Unnamed: 859, 860: Unnamed: 860, 861: Unnamed: 861, 862: Unnamed: 862, 863: Unnamed: 863, 864: Unnamed: 864, 865: Unnamed: 865, 866: Unnamed: 866, 867: Unnamed: 867, 868: Unnamed: 868, 869: Unnamed: 869, 870: Unnamed: 870, 871: Unnamed: 871, 872: Unnamed: 872, 873: Unnamed: 873, 874: Unnamed: 874, 875: Unnamed: 875, 876: Unnamed: 876, 877: Unnamed: 877, 878: Unnamed: 878, 879: Unnamed: 879, 880: Unnamed: 880, 881: Unnamed: 881, 882: Unnamed: 882, 883: Unnamed: 883, 884: Unnamed: 884, 885: Unnamed: 885, 886: Unnamed: 886, 887: Unnamed: 887, 888: Unnamed: 888, 889: Unnamed: 889, 890: Unnamed: 890, 891: Unnamed: 891, 892: Unnamed: 892, 893: Unnamed: 893, 894: Unnamed: 894, 895: Unnamed: 895, 896: Unnamed: 896, 897: Unnamed: 897, 898: Unnamed: 898, 899: Unnamed: 899, 900: Unnamed: 900, 901: Unnamed: 901, 902: Unnamed: 902, 903: Unnamed: 903, 904: Unnamed: 904, 905: Unnamed: 905, 906: Unnamed: 906, 907: Unnamed: 907, 908: Unnamed: 908, 909: Unnamed: 909, 910: Unnamed: 910, 911: Unnamed: 911, 912: Unnamed: 912, 913: Unnamed: 913, 914: Unnamed: 914, 915: Unnamed: 915, 916: Unnamed: 916, 917: Unnamed: 917, 918: Unnamed: 918, 919: Unnamed: 919, 920: Unnamed: 920, 921: Unnamed: 921, 922: Unnamed: 922, 923: Unnamed: 923, 924: Unnamed: 924, 925: Unnamed: 925, 926: Unnamed: 926, 927: Unnamed: 927, 928: Unnamed: 928, 929: Unnamed: 929, 930: Unnamed: 930, 931: Unnamed: 931, 932: Unnamed: 932, 933: Unnamed: 933, 934: Unnamed: 934, 935: Unnamed: 935, 936: Unnamed: 936, 937: Unnamed: 937, 938: Unnamed: 938, 939: Unnamed: 939, 940: Unnamed: 940, 941: Unnamed: 941, 942: Unnamed: 942, 943: Unnamed: 943, 944: Unnamed: 944, 945: Unnamed: 945, 946: Unnamed: 946, 947: Unnamed: 947, 948: Unnamed: 948, 949: Unnamed: 949, 950: Unnamed: 950, 951: Unnamed: 951, 952: Unnamed: 952, 953: Unnamed: 953, 954: Unnamed: 954, 955: Unnamed: 955, 956: Unnamed: 956, 957: Unnamed: 957, 958: Unnamed: 958, 959: Unnamed: 959, 960: Unnamed: 960, 961: Unnamed: 961, 962: Unnamed: 962, 963: Unnamed: 963, 964: Unnamed: 964, 965: Unnamed: 965, 966: Unnamed: 966, 967: Unnamed: 967, 968: Unnamed: 968, 969: Unnamed: 969, 970: Unnamed: 970, 971: Unnamed: 971, 972: Unnamed: 972, 973: Unnamed: 973, 974: Unnamed: 974, 975: Unnamed: 975, 976: Unnamed: 976, 977: Unnamed: 977, 978: Unnamed: 978, 979: Unnamed: 979, 980: Unnamed: 980, 981: Unnamed: 981, 982: Unnamed: 982, 983: Unnamed: 983, 984: Unnamed: 984, 985: Unnamed: 985, 986: Unnamed: 986, 987: Unnamed: 987, 988: Unnamed: 988, 989: Unnamed: 989, 990: Unnamed: 990, 991: Unnamed: 991, 992: Unnamed: 992, 993: Unnamed: 993, 994: Unnamed: 994, 995: Unnamed: 995, 996: Unnamed: 996, 997: Unnamed: 997, 998: Unnamed: 998, 999: Unnamed: 999, 1000: Unnamed: 1000, 1001: Unnamed: 1001, 1002: Unnamed: 1002, 1003: Unnamed: 1003, 1004: Unnamed: 1004, 1005: Unnamed: 1005, 1006: Unnamed: 1006, 1007: Unnamed: 1007, 1008: Unnamed: 1008, 1009: Unnamed: 1009, 1010: Unnamed: 1010, 1011: Unnamed: 1011, 1012: Unnamed: 1012, 1013: Unnamed: 1013, 1014: Unnamed: 1014, 1015: Unnamed: 1015, 1016: Unnamed: 1016, 1017: Unnamed: 1017, 1018: Unnamed: 1018, 1019: Unnamed: 1019, 1020: Unnamed: 1020, 1021: Unnamed: 1021, 1022: Unnamed: 1022, 1023: Unnamed: 1023, 1024: Unnamed: 1024, 1025: Unnamed: 1025, 1026: Unnamed: 1026, 1027: Unnamed: 1027, 1028: Unnamed: 1028, 1029: Unnamed: 1029, 1030: Unnamed: 1030, 1031: Unnamed: 1031, 1032: Unnamed: 1032, 1033: Unnamed: 1033, 1034: Unnamed: 1034, 1035: Unnamed: 1035, 1036: Unnamed: 1036, 1037: Unnamed: 1037, 1038: Unnamed: 1038, 1039: Unnamed: 1039, 1040: Unnamed: 1040, 1041: Unnamed: 1041, 1042: Unnamed: 1042, 1043: Unnamed: 1043, 1044: Unnamed: 1044, 1045: Unnamed: 1045, 1046: Unnamed: 1046, 1047: Unnamed: 1047, 1048: Unnamed: 1048, 1049: Unnamed: 1049, 1050: Unnamed: 1050, 1051: Unnamed: 1051, 1052: Unnamed: 1052, 1053: Unnamed: 1053, 

In [8]:
credits.head()

,movie_id,title,cast,crew,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124